# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Cqh_files/2021verilog/upload/lab3/lab3_2/lab3_2.cache/wt [current_project]
set_property parent.project_path F:/Cqh_files/2021verilog/upload/lab3/lab3_2/lab3_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/Cqh_files/2021verilog/upload/lab3/rom8x4.v
  F:/Cqh_files/2021verilog/upload/lab3/pattern.v
  F:/Cqh_files/2021verilog/upload/lab3/divider.v
  F:/Cqh_files/2021verilog/upload/lab3/counter.v
  F:/Cqh_files/2021verilog/upload/lab3/decoder3_8.v
  F:/Cqh_files/2021verilog/upload/lab3/dynamic_scan.v
}
read_xdc F:/Cqh_files/2021verilog/upload/lab3/Nexys4DDR_Master3.xdc
set_property used_in_implementation false [get_files F:/Cqh_files/2021verilog/upload/lab3/Nexys4DDR_Master3.xdc]

synth_design -top dynamic_scan -part xc7a100tcsg324-1
write_checkpoint -noxdef dynamic_scan.dcp
catch { report_utilization -file dynamic_scan_utilization_synth.rpt -pb dynamic_scan_utilization_synth.pb }
